### ISSUE TITLE
開始時刻を入力したら、終了時刻の初期表示は開始時刻にしたい

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#100]

**Comment by ernix** [comment]
done
23879af586ebf4a815782fa1da481035b257232b

JSとしてではなく開始日時と終了日時のチェックはロジック側にも必要かも。

ついでに今までは一旦値が入ってしまうとdatetimepickerが動かなかったので
datetimepicker用に右側にアイコンを設置した。

![screen shot 2016-08-21 at 12 23 36 pm](https://cloud.githubusercontent.com/assets/343556/17839366/35686fae-679a-11e6-9f9a-d6fbcc794633.png)
