### ISSUE TITLE
ログイン時の失敗画面が__all__などプリントデバッグになっている

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#101]
エラー表記になっていない。

**Comment by keitakurita** [comment]
これ、djangoのユーザー認証をいじらないといけないっぽいけど、djangoのユーザー認証のファイルはappの上のdirectoryにあるため、このgitのprojectの範囲内では修正できない...気がする...

**Comment by ernix** [comment]
あれ、そうだっけ？テンプレートの中に書いてあったような

**Comment by keitakurita** [comment]
すみません、エラーメッセージをカスタマイズする話だと思ってました！
エラーが出た時「ログインに失敗しました」というエラーだけをはかせることはできますが、とりあえずはデバッグ用に詳細なエラーを表示した方がいい気がします

**Comment by ernix** [comment]
done
42b441d8cbc6b98567e736f8620bd20f03c4662e
