### ISSUE TITLE
グループを作成するときに関連付けるイベントがユニークでないイベント名からしか判断できない

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#105]
> どの「test」？
> ![screen shot 2016-08-19 at 3 42 30 pm](https://cloud.githubusercontent.com/assets/343556/17826275/d494048a-6623-11e6-89bc-141db622e4b7.png)

**Comment by keitakurita** [comment]
日程の情報も付け加えました
（ユニークではないですが、同じ日に同じイベントを複数開催することは現実的にないと見て、実質ユニークと考えました）
