### ISSUE TITLE
作成したユーザの削除機能

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#11]

**Comment by MURAKOSHITAKAHIRO** [comment]
以下のサイトで管理者がユーザーを削除できるようになっているのでcloseします。

■ログイン | Django サイト管理
https://sovol.moe/admin/login/?next=/admin/

**Comment by MURAKOSHITAKAHIRO** [comment]
close #12

**Comment by MURAKOSHITAKAHIRO** [comment]
close #12
