### ISSUE TITLE
ユーザ情報の生年月日にdatetimepickerが使えない

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#110]
使いたい

**Comment by ernix** [comment]
必須項目だったみたい。
プロフィール変更にエラーが出なかったのでわからなかった。
エラーを出すようにした。

c0c86eac494e181841a2f2e232bc05b4ca2a46e8

**Comment by swdrsk** [comment]
年の指定に向いてない気がする（1980年とか）ので生年月日はプルダウンがいい気がするのですがどうでしょう。

**Comment by ernix** [comment]
@swdrsk +1

**Comment by tasugi** [comment]
#145 と重複しているのでこれはクローズします
