### ISSUE TITLE
新着ボランティア情報が、ログイン後のダッシュボードにも表示されるといい

### ISSUE THREAD

**Issue by ayk4580** [internship2016/sovolo#113]

**Comment by ayk4580** [comment]
検索ボックスに何も入力せずに検索すると、新着ボランティア情報が表示されるそうですが、そのやり方だと分りにくいので、ダッシュボードにも表示してほしい。数が多すぎると嫌なので、新着の5件くらい。

**Comment by tasugi** [comment]
表示するようにしました
