### ISSUE TITLE
イベントの時刻情報を、わかりやすくstrに変換する

### ISSUE THREAD

**Issue by keitakurita** [internship2016/sovolo#116]
できれば、
(曜日), MM-DDとしたい。

**Comment by ernix** [comment]
done
870e96c0207ce6f78a904d7ad90e8969e2cbdb05

`STRPTIME(3)`とフォーマット全然違うのキモいけど、解決はできる。
ref: https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#date
