### ISSUE TITLE
ページにメールアドレスが出てくるのはいいのか？

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#122]
登録した連絡先にメールアドレスがイベント詳細に出てきますが、
スパムメールへの懸念もあり出すべきではない気がします。

せめてプロフィールで連絡先の公開非公開を設定できるようにし、
表示はオプトアウトしたほうがよくないですか？

**Comment by tntktnx** [comment]
イベントに連絡先を登録でき、その新規作成時のデフォルト値がユーザの登録アドレスになっています。
