### ISSUE TITLE
中身のないパネルは表示から外すか、もしくは「（空）」などの表記を入れたほうがいい

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#127]
中身のないパネルは表示しないか、何かデフォルトの表示があったほうが良さそうに思います。

![screen shot 2016-08-20 at 7 27 04 pm](https://cloud.githubusercontent.com/assets/343556/17834955/35ef47ce-670c-11e6-84a9-fffda87e2ec5.png)

**Comment by keitakurita** [comment]
解決しました
