### ISSUE TITLE
空文字列でイベント検索すると直感に反してすべてが表示される。

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#134]
検索テキストボックスに何も入れないで検索してもイベント一覧が表示されますが、これは仕様ですか？
この場合、どういう基準で表示しているのでしょう？(すべてのイベント？)

**Comment by tntktnx** [comment]
仕様です。

**Comment by ernix** [comment]
空のクエリに対してはすべてのイベントが出ます。
