### ISSUE TITLE
有効な開催期間を入力しているのにイベントのステータスが「終了」になる

### ISSUE THREAD

**Issue by caliconeko** [internship2016/sovolo#137]
正しい開催期間を入力していると思うのだが、新着の所に「終了」と表示されている。

**Comment by ernix** [comment]
@Cheresta もう少し詳しく再現手順を教えてもらえますか？

**Comment by swdrsk** [comment]
開始時刻を過ぎれば終了時刻に満たなくても終了になっていたからかもしれません。
開催中は「開催中」と表示するよう変更しました。
そうでない変な表示があれば教えていただけますか。
