### ISSUE TITLE
ログイン画面のエラーメッセージとエラーを発生させたフォームのラベルが合っていない

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#139]
テキストボックスのラベルは `Email` と `パスワード` なのに、エラーメッセージでは `username` と `password` と表示されます。
ラベルと揃えるべきだと思います。

**Comment by tasugi** [comment]
#150

**Comment by tntktnx** [comment]
@scirocco0316 
こちら再現ができていないのですが、どのように入力するとusername, passwordという表示がされるのでしょうか？
