### ISSUE TITLE
ユーザー登録画面のエラーメッセージがエラーを発生させたフォームのラベルと一致しない

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#142]
テキストボックスのラベルは `Email`、`パスワード`、`Username` なのに、エラーメッセージでは `email`、`password`、`username` と表示されます。
また、テキストボックスの順番とエラーメッセージの順番が一致していません。

**Comment by tasugi** [comment]
#150 と関連してそう

**Comment by ernix** [comment]
![screen shot 2016-08-24 at 4 33 41 pm](https://cloud.githubusercontent.com/assets/343556/17951665/aff9221a-6a18-11e6-943a-de2ac48b30c1.png)

**Comment by haraguchijouji** [comment]
解消されているようです。
