### ISSUE TITLE
パスワードのバリデーション機能が有効になっていない

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#144]
ユーザー登録でパスワードが1文字でも登録できてしまいました。

**Comment by swdrsk** [comment]
パスワード二回入力は必要かと

**Comment by ernix** [comment]
`AUTH_PASSWORD_VALIDATORS`が設定されているにもかかわらず効いてない気がする。
通常のcreate_userではない？？

**Comment by tasugi** [comment]
これはエンハンスメントで

**Comment by MURAKOSHITAKAHIRO** [comment]
パスワードは一文字でも登録が可能のまま。
パスワード二回入力は必要かもしれないが、後回しにします。
