### ISSUE TITLE
プロフィールの生年月日がフリーワードになっていて入力の書式がわからない

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#145]
- テキストボックスのラベルは "生年月日" なのに、エラーメッセージでは "birthday" と表示されます。
- 同じエラーメッセージが2つ表示されます。
- テキストボックスだとどういう書式で入力していいのかが分かりにくいです。

例えば、区切りに / を使うとエラーになります。
プルダウンの方がよいと思います。

**Comment by swdrsk** [comment]
直しました。
