### ISSUE TITLE
ラベルとエラーメッセージの対応が取れていない

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#146]
全体的に言えることですが、入力フォームのラベルとエラーメッセージでのその項目の名前の対応が取れていません。
エラーメッセージでは内部的な変数名が表示されるようになっているように見えますが、ラベルと揃えるべきでしょう。
例えば、プロフィール編集画面で "ニックネーム" という項目がありますが、エラーメッセージでは "username" と表示されます。
エラーメッセージでも "ニックネーム" と表示するべきでしょう。

**Comment by ernix** [comment]
以下の問題と同じと見做し、このチケットは一旦クローズします。
事実と異なる場合はチケットを再オープンしてください。

https://github.com/internship2016/sovolo/issues/142
https://github.com/internship2016/sovolo/issues/139
