### ISSUE TITLE
プロフィール編集画面でエラーが発生するとエラーメッセージが2つ表示される

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#147]
ニックネーム、Email、プロフィール画像のエラーメッセージで、同じものが2つ表示されます。

**Comment by ernix** [comment]
あー・・・私が自前で入れた c0c86eac494e181841a2f2e232bc05b4ca2a46e8 とダブってる感じです。一旦私の方をRevertします。

**Comment by ernix** [comment]
done
2792221acc95e4d698ca739f2c006a7d3474a109

**Comment by scirocco0316** [comment]
今試してみたのですが、まだ直っていないように見えます。

**Comment by ernix** [comment]
@scirocco0316 
再現しませんでした。スクリーンショットを送ってもらえますか？

![screen shot 2016-08-22 at 10 05 44 am](https://cloud.githubusercontent.com/assets/343556/17863815/2c029ad2-6850-11e6-89e4-ff771e897b1e.png)

**Comment by scirocco0316** [comment]
今は直っていました。
私が試したときはまだ反映されてなかったようです。
