### ISSUE TITLE
イベント作成

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#15]
入力例が無いので入力書式が不明

**Comment by ernix** [comment]
@haraguchijouji watermarkがあればいいってこと？

**Comment by haraguchijouji** [comment]
「watermark」-->そうです。

Region項目の表示順が「佐賀県」から始まっている

**Comment by ernix** [comment]
@haraguchijouji ソート順の問題に関しては https://github.com/internship2016/sovolo/issues/6 を見てください。

**Comment by haraguchijouji** [comment]
「Ticket」にチェックつけると何ができるの？

**Comment by haraguchijouji** [comment]
「details」に入力したが「説明」の表示欄に何も表示されない

**Comment by keitakurita** [comment]
日時をdatetime pickerで指定できるようにしたい。
yy-mm-dd 00:00:00という書式で送ってほしい。

**Comment by haraguchijouji** [comment]
主催者が自動で
主催者：2
になっているのはなぜ？

**Comment by haraguchijouji** [comment]
https://sovolo.earth/event/2/#のページで
「参加」ボタンをクリックしても何も変わらなかった。
クリック前の「参加状況」表示は4人/4人になっていた。
参加人数の制限等の入力は行った覚えがない。

**Comment by haraguchijouji** [comment]
イベント作成後、再度ログインした時に作成したイベントが見当たらない。

**Comment by haraguchijouji** [comment]
https://sovolo.earth/#のページで
「イベント検索」で「検索」ボタンを押すとエラー

**Comment by haraguchijouji** [comment]
Top Pageで「所属グループの新着」「自分の地域の新着イベント」のリストにイベント名が表示されない。
「画像」からのリンク先では表示される。

**Comment by haraguchijouji** [comment]
ログアウト状態でも作成したイベントで「DELETE」ボタンが見える。
クリックすると「アクセス権が無い」エラーになる。

**Comment by swdrsk** [comment]
フッターが邪魔でイベント作成ボタンが押せない

**Comment by ernix** [comment]
フッターが邪魔する問題は以下のコミットで修正しました: 40f47ac

**Comment by ernix** [comment]
間違えて閉じちゃった

**Comment by tasugi** [comment]
日付入力はカレンダーからすることに決まったので終了
