### ISSUE TITLE
イベント作成画面でエラーが発生すると、既存の入力項目が消える

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#150]
・エラーがあった場合に、入力した内容が消えてしまいます。
・エラーメッセージが同じものが2つ表示されます。

**Comment by tasugi** [comment]
現在は、送信前にjavascript側でデータが正常なものかチェックをかけています。
正しくないデータが送信できてしまうということはjavascriptでのチェックに漏れがあるのかもしれません。
どういった情報を入力するとエラーになるのかわかるのであれば教えていただけると幸いです。

**Comment by ernix** [comment]
問題再現しました。ボランティア名に空白のみを入力してください。
JavaScriptのチェックが入力値のチェックをやるのに対して、サーバ側では入力値をトリムしてから値を評価しているように見えます。

**Comment by ernix** [comment]
サーバサイドでエラーを評価して最後の入力値をフォームに入れなおそうとする場合、セッションに入力データを持たせる必要があります。

**Comment by scirocco0316** [comment]
> どういった情報を入力するとエラーになるのかわかるのであれば教えていただけると幸いです。

何も入力しないで送信すればエラーになります。
あと、JavaScript でのエラーチェックが効いてないように見えます。
効いていれば即座にエラーが表示されると思うのですが、若干タイムラグがあり、エラーがあってもサーバに接続しに行っているように見えます。

**Comment by tntktnx** [comment]
HTML5のinputの各種attributeがSafariで動作しないのが原因のようです。
