### ISSUE TITLE
イベント作成画面で管理者のテキストボックスが空でも追加できてしまう

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#154]
イベント作成画面で、"管理者" のテキストボックスに何も入力しない状態でも、"追加" ボタンを押すとチェックボックスが追加されます。

**Comment by tntktnx** [comment]
修正しました

**Comment by scirocco0316** [comment]
今試してみたところ、まだ直っていないようでした。
ブラウザは Safari で試しました。

**Comment by ernix** [comment]
多分sovolo.earthに反映されていないからだと思います。
フッタにある'rev'のリンクを辿ってください。修正したコミットが入っていなかったりしませんか？

**Comment by ernix** [comment]
@scirocco0316 
再現しませんでした。safariで試しています。

**Comment by scirocco0316** [comment]
今は直っていました。
