### ISSUE TITLE
主催者、管理者、参加者の表示

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#155]
仕様なのか分からないのですが、イベント詳細画面で、主催者は名前が表示されているのに、管理者と参加者は画像だけです。

**Comment by tntktnx** [comment]
主催者は一人しかいないので名前付き、管理者は複数設置可能なのでアイコンリスト、という仕様になっています。

**Comment by scirocco0316** [comment]
了解しました。
