### ISSUE TITLE
検索結果の開催日のフォーマット

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#156]
検索結果表示ページで、イベントの開催日が "(土), 8-20" のようになっていますが、"8/20 (土)" の方が一般的でしょう。

**Comment by ernix** [comment]
https://github.com/internship2016/sovolo/issues/116

そうね。私もそう思う。8/20 (土)

**Comment by ernix** [comment]
done
4cab07f9f0644b6667c1b954b9c6bdeb40d4dcc6
