### ISSUE TITLE
SNSでシェアするボタンの先が一緒

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#157]
ボランティアの名前あたりは動的に挿入したい。
![screen shot 2016-08-21 at 11 53 41 pm](https://cloud.githubusercontent.com/assets/343556/17845987/a675e522-67fa-11e6-8dbc-c53fbbfdc1f0.png)

**Comment by ernix** [comment]
あとリンク

**Comment by swdrsk** [comment]
ソーシャルシェアボタンが今のところデフォルトのリンクになっています。参考にしたサイトを貼っておきますので運用するＵＲＬが決まったら変えてもらえればと思います。

[9:57]  
facebook: https://developers.facebook.com/docs/plugins/like-button

twitter: https://about.twitter.com/ja/resources/buttons#tweet

**Comment by tasugi** [comment]
Twitterについては、ページのタイトルをツイート文に含ませるようにしました。
FBについては手元でテストできないので保留で。
そもそもFBでシェアするときってデフォルトメッセージみたいなのあったっけ？

**Comment by swdrsk** [comment]
FBもやってみました。今のところうまくいくか保証はないです。
バランスが悪いと思ったのでいいねボタンをとってシェアボタンだけにしてみました。
ＦＢのデフォルトメッセージはないんじゃないかな。
