### ISSUE TITLE
イベント主催者はどのようにして参加者の登録具合を俯瞰すればよいのかわからない

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#159]
[社内からのフィードバック]

フロントエンドにもう少し工夫が必要です。まだ未完成で構想にあるならスルーして下さい。

現状では、災害ボランティアの募集ページというよりゆるいサークルやイベントの募集にしか見えません。
自分が使う側だとしたら、具体的に災害地の場所を画像で確認したいです。できればmap上で道路とか川が行けるのか否かとかいう情報も含めてね。
画像があると臨場感が伝わると思いますから投稿機能ももちろん必要でしょう。

また、最新のニュースをRSSとかで集めてトップに表示するとそれっぽくなるかもしれませんね。

例えばAの地域で募集をかけた主催者はその集まり具合を見たいと思う。
またA地域で複数募集をかけた時にどうなるのかとか、それを調整できるのかとかetc・・

**Comment by ernix** [comment]
災害時のボランティア活動にも利用できるイベントの募集プラットフォームという位置づけになっています。
サービスを災害のみに特化してしまうと、災害が無い時はサービスが閑散として開店休業状態になってしまいます。
普段使われていない放ったらかしのサービスがいざ災害発生時に問題なく動くかというと・・・おそらくトラブルまみれでしょう。

そのため災害のみならず、普段のボランティア活動にも活用していただけるようなサービスを目指しています。
また、災害のみを期待するサービスというのも少々不謹慎な向きがあるように感じています。

**Comment by ernix** [comment]
mapや画像の追加に関しては同意。

**Comment by ernix** [comment]
RSSに関しては、こちらのチケットと重複:
https://github.com/internship2016/sovolo/issues/130

**Comment by ernix** [comment]
また、「ゆるいイベントやサークルの募集」に見えたのは、
デフォルトの画像が与える先入観のせいでしょう。
これはもっとデフォルトっぽい画像に修正される予定です。

![party](https://cloud.githubusercontent.com/assets/343556/17913166/2f06f9e6-694d-11e6-9c1a-46ad3b85a29a.jpg)

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
