### ISSUE TITLE
タグが無い

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#171]
検索側とイベント側に実装されてない感

**Comment by ernix** [comment]
seed_dataがはいってないとこんな感じ
![screen shot 2016-08-22 at 3 25 01 pm](https://cloud.githubusercontent.com/assets/343556/17873825/b1ed1fc4-687c-11e6-8ad8-14611763f4fd.png)

**Comment by tasugi** [comment]
シードデータを入れてないのが原因でした

**Comment by ernix** [comment]
Readme.mdのINSTALL手順に追加してもらえるとありがたみ。
ぜんぶおじゃんになっちゃってはじめから建てなおさないといけない場合を想定して。
