### ISSUE TITLE
各所の参加者リストに管理者が表示されてしまっている

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#172]
https://sovolo.earth/event/3/

![screen shot 2016-08-22 at 4 07 03 pm](https://cloud.githubusercontent.com/assets/343556/17874778/9adbfee4-6882-11e6-8867-6678138a0d4e.png)

**Comment by tntktnx** [comment]
管理者(1) + 興味あり(1) + 参加者(2)
興味ありは古い機能で、flushしない限り消えない
