### ISSUE TITLE
「参加予定のボランティア」に参加中のイベントが表示されない

### ISSUE THREAD

**Issue by ayk4580** [internship2016/sovolo#173]
現在参加中なのは以下の2件
・日ノ出町公園ごみ拾い
・行方不明ペット情報交換会
管理者なのは以下の2件
・神楽坂祭り交通整理
・東京パラリンピック会場での通訳
合計4件のはずが、参加予定のボランティアには3件のみ表示されています。
![2016-08-23 08 13 53](https://cloud.githubusercontent.com/assets/21133940/17874994/12b23bea-690a-11e6-9f45-c95e3f8c58c4.png)
![2016-08-23 08 14 06](https://cloud.githubusercontent.com/assets/21133940/17875010/218d5f28-690a-11e6-92f4-cb548c1f32d7.png)

**Comment by keitakurita** [comment]
sovolo.earthをアップデートしましたが、これでどうでしょうか？

**Comment by ayk4580** [comment]
@keitakurita 確認しました。正しく表示されています。
