### ISSUE TITLE
イベントへのコメントに画像投稿機能がほしい

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#188]
#159

**Comment by ernix** [comment]
欲を言えばマークダウン書きたいですね。
リンク貼りたい需要は必ずあると思います。

**Comment by swdrsk** [comment]
イベントのコメントだけでなく、連絡事項やイベント・グループの説明にもマークダウンは将来的に必須かなと。
ユーザー目線で考えれば、グループの説明からグループのＨＰやＦＢページに飛んで欲しい気がする。

**Comment by MURAKOSHITAKAHIRO** [comment]
未登載ですが、いったん閉じます。
