### ISSUE TITLE
イベント作成時のエラー表示

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#191]
現在、イベント作成時のエラーはページの上部に表示されますが、ログイン画面ではエラーがあったフィールドの下に表示されるので、揃えた方がいいと思います。
もし、表示位置を現在のままにするのであれば、変数名ではなくラベル名を表示するべきかと思います。
// 例: "details" ではなく "詳細説明" とする

**Comment by keitakurita** [comment]
どのような手順を踏めばイベント作成時にエラーが発生するか教えていただけますか？

**Comment by scirocco0316** [comment]
必須フィールドに入力しないでフォームを送信した場合です。
手っ取り早いのは、何も入力しないで送信すれば再現します。

**Comment by ernix** [comment]
Safariが一部のHTML5の機能をサポートしていないことが原因です。
inputタグのrequired要素やpattern要素は素のSafariではサポートされていません。
とりあえずSafariでサポートを有効にするpolyfillを突っ込んだのでクライアントサイドのチェックは走るようになったと思います。

https://github.com/internship2016/sovolo/commit/cd32c96af7b6c4dcf8cc65105556c61ccb44ab45
