### ISSUE TITLE
ボランティアページ: タグのテキストだけサイズがでかい

### ISSUE THREAD

**Issue by tntktnx** [internship2016/sovolo#211]
タグのテキストだけサイズがでかい

**Comment by tasugi** [comment]
意図的に大きくしたんだけど気持ち悪い？

**Comment by tntktnx** [comment]
@tasugi 
どういう意図？

**Comment by tasugi** [comment]
@tntktnx ただのテキストとは役割が違うことを見た目でも明らかにしたかった

**Comment by keitakurita** [comment]
@tasugi 他のリンクもわざわざ大きくしていないし、タグがリンクになっているであろうことは慣習的にわかっているだろうから、あまり大きくする必要はないのでは？

**Comment by tasugi** [comment]
1:2で気持ち悪い派のほうが多いから、大きさは他と一緒にしようと思います！
