### ISSUE TITLE
イベントページ: 現状の位置では、参加後、参加者への連絡事項が増えたことに気づかないのでは

### ISSUE THREAD

**Issue by tntktnx** [internship2016/sovolo#215]

**Comment by keitakurita** [comment]
そのためのメール通知なのでは？

**Comment by tntktnx** [comment]
むしろ、メール通知はその時点で参加している人にしか届かないから、このフィールドを作るという話になったと記憶しているけれど。

**Comment by keitakurita** [comment]
参加している人以外が、参加者への連絡事項が増えたことを確認する必要はあるかな？

**Comment by tntktnx** [comment]
参加している人以外には、そもそも表示されてない
参加後に、その表示が新しく見えるようになっているから、そのことを知覚させないといけない

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
