### ISSUE TITLE
デフォルト画像の選定

### ISSUE THREAD

**Issue by tntktnx** [internship2016/sovolo#229]

**Comment by tntktnx** [comment]
https://en.wikipedia.org/wiki/Volunteering#/media/File:CI_boardwalk_Sandy_sweepers_jeh.jpg

**Comment by keitakurita** [comment]
プロフィール画像候補１：
![1472169518_profile01](https://cloud.githubusercontent.com/assets/17820446/17982133/738d014a-6abb-11e6-8d66-529436f0ac26.png)

プロフィール画像候補２：
![1472169708_user](https://cloud.githubusercontent.com/assets/17820446/17982230/d760be5a-6abb-11e6-8337-5c21e1d01436.png)

グループ画像候補：
![1472169723_group2](https://cloud.githubusercontent.com/assets/17820446/17982243/e55917b4-6abb-11e6-9ffe-41cf5d45bea2.png)

**Comment by keitakurita** [comment]
とりあえず解決
