### ISSUE TITLE
トップページにキャッチフレーズを追加する: 人と人とを結ぶ、ボランティアスクウェア

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#245]
Sovolのキャッチフレーズとして「人と人とを結ぶ、ボランティアスクウェア」

**Comment by ernix** [comment]
@haraguchijouji もう少し修正内容を具体的にお願いします。
キャッチフレーズをトップページに載せるのですか？

**Comment by haraguchijouji** [comment]
[Sovol、ここを直してほしい.pptx](https://github.com/internship2016/sovolo/files/1035166/Sovol.pptx)

**Comment by ernix** [comment]
![screen shot 2017-05-29 at 17 06 20](https://cloud.githubusercontent.com/assets/343556/26541588/3874f59e-4491-11e7-8e48-0841283eae43.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
