### ISSUE TITLE
地図と日時を中心にマッチングを構成させる

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#246]

**Comment by ernix** [comment]
@haraguchijouji 具体的にお願いします。現在何がそうなっていなくて、どうさせる必要がある、というふうに。

**Comment by haraguchijouji** [comment]
地図上で「現在募集中のボランティア」が「フラグ」で表示されている状態で「日時」「タグ」で絞り込みができるようにしたい。

**Comment by haraguchijouji** [comment]
![default](https://user-images.githubusercontent.com/8582641/27121401-2091fa2e-5122-11e7-9826-df485fb8269a.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
実装されているので閉じます。
