### ISSUE TITLE
イベント表示「参加」

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#25]
https://sovolo.earth/event/2/#のページで
「参加」ボタンをクリックしても何も変わらなかった。
クリック前の「参加状況」表示は4人/4人になっていた。
参加人数の制限等の入力は行った覚えがない。
--->表示されなくなっている

**Comment by haraguchijouji** [comment]
「参加する」ボタンはリンク先ファイルがない？

**Comment by swdrsk** [comment]
参加するボタン、枠の上限は表示出来るようにした
現在参加人数、上限がない場合の表示はまだ。
