### ISSUE TITLE
メッセージ機能と通知機能

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#252]

**Comment by ernix** [comment]
@haraguchijouji もう少し具体的にお願いします。
どこに「メッセージ機能」が必要で、どのように「通知」すべきか。（メール？

**Comment by haraguchijouji** [comment]
「メッセージ機能」：ボランティアをする人とされる人が連絡を取り合う機能がほしい。
「通知」：「複数参加のボランティアでは参加者一斉通知機能がほしい」
「方式」：「メール」「twitter」「Line」「message」等複数の方式でほしい

**Comment by MURAKOSHITAKAHIRO** [comment]
LineとMessageが無いが問題ないと思うので閉じます。
