### ISSUE TITLE
「おすすめボランティア」を少しだけ表示する

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#258]

**Comment by ernix** [comment]
@haraguchijouji 何に従って「おすすめ」とするのかを詳しく教えてください。現在も「新着」のおすすめは出ています。

**Comment by haraguchijouji** [comment]
「新着」ではなく「おすすめ」としたい。
「期間」が合って「近所」の情報を数個（3個ほど）トップに表示する。

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
