### ISSUE TITLE
Web広告欄を用意する

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#259]

**Comment by ernix** [comment]
@haraguchijouji 具体的にお願いします。「誰が」「何を」「どこに」用意できるようにするのか。
応募者や参加者が自分のページでアフィリエイトできるようにしたいという意味ですか？

**Comment by haraguchijouji** [comment]
「誰が」：「インターリンクが（またはSoVol運用団体が）」
「何を」：「Sovolに広告を載せたい人（団体）の広告を」
「どこに」：「ページの隅に」
載せられるようなエリアを予め確保しておく。

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
