### ISSUE TITLE
地図を中心とした検索

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#260]
![default](https://cloud.githubusercontent.com/assets/8582641/26535937/f5ad3a2e-446c-11e7-8615-d5c225ac3268.png)

**Comment by ernix** [comment]
これは以下の issue と重複しているように見えます。合っていますか？
https://github.com/internship2016/sovolo/issues/246

**Comment by haraguchijouji** [comment]
合ってます。
#246に総合出来ますか？

**Comment by ernix** [comment]
こちらはクローズします。
