### ISSUE TITLE
カテゴリのアイコンでボランティアの概要が判るようにする。

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#262]

**Comment by ernix** [comment]
@haraguchijouji 「カテゴリ」とは「タグ」のことですか？
例えば医療関係のボランティアには医療アイコンを使用する等。

**Comment by haraguchijouji** [comment]
そうです。
以下の詳細ページにタイトルの左にある「唇」の様なタグアイコンで纏める。
![default](https://user-images.githubusercontent.com/8582641/27121526-b73e7114-5122-11e7-8bed-20828782971a.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
