### ISSUE TITLE
場所の情報は大きく表示する

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#263]
![default](https://cloud.githubusercontent.com/assets/8582641/26535966/419551f6-446d-11e7-8f7e-41b5578df7a7.png)

**Comment by ernix** [comment]
@haraguchijouji 添付画像のように、現在よりも大きくさせたいということですか？

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
