### ISSUE TITLE
興味のあるカテゴリーや参加予定のボランティアの内容はアイコン化で表示する

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#265]
![default](https://cloud.githubusercontent.com/assets/8582641/26535981/780fb82a-446d-11e7-8261-2e3aeff216d9.png)

**Comment by ernix** [comment]
@haraguchijouji アイコンはどれぐらいの種類があれば適当だと思われますか？

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
