### ISSUE TITLE
ボランティアをしてほしい人が発信する場合の流れ

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#273]
1. されたい人がやってほしいボランティアを登録
2. したい人が検索
3. したい人が「できます宣言」
4. マッチングしたら詳細をやりとり
5. ボランティア実施
6. レビュー

**Comment by haraguchijouji** [comment]
[sovol社内向け提案最終盤_201703.pptx](https://github.com/internship2016/sovolo/files/1073972/sovol._201703.pptx)

**Comment by ernix** [comment]
@haraguchijouji このファイルの内容に公開に適さない情報が入っていると判断しました。一旦ファイルを削除したので修正の上上げなおしてください。

**Comment by ernix** [comment]
ボカシを入れてメタデータを削除し、PDFに焼き直しました。
[sovol_201703.pdf](https://github.com/internship2016/sovolo/files/1076327/sovol_201703.pdf)

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
