### ISSUE TITLE
ボランティアをしたい人が発信する場合の流れ

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#274]
1. したい人ができる内容と日時を登録
2. されたい人が検索
3. されたい人が「リクエスト」
4. マッチングしたら詳細をやりとり
5. ボランティア実施
6. レビュー

**Comment by haraguchijouji** [comment]
[sovol社内向け提案最終盤_201703.pptx](https://github.com/internship2016/sovolo/files/1073968/sovol._201703.pptx)

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
