### ISSUE TITLE
検索画面

### ISSUE THREAD

**Issue by kurarrr** [internship2016/sovolo#277]
- 8/9で検索すると8/9だけでなく8/9以降のものが出てくる(それ自体は別にいいがわかりにくい)
- 範囲で検索したい
- 終了済みを表示しないようにしていても自分の主催イベントは出てくる
- 終了済み検索うまく昨日してないっぽい
- 検索で日付を必ずしも指定しなくてもいい方が良さそう

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
