### ISSUE TITLE
イベント

### ISSUE THREAD

**Issue by kurarrr** [internship2016/sovolo#278]
- イベント詳細画面で参加しても参加者の%変わらない
- タグ自分で作成できるようにした方がいいのでは

**Comment by kurarrr** [comment]
- イベントの管理者追加でid入れたら候補ユーザー出るようにしたい
- せっかくグループあるからグループから追加できるようにもした方がいいのでは
- グループにイベント参加リクエストとか送れたい

**Comment by haraguchijouji** [comment]
グループ機能は削除

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
