### ISSUE TITLE
コード疑問点　柴山

### ISSUE THREAD

**Issue by shiba0004** [internship2016/sovolo#279]
views.py 　の中にある

@method_decorator(login_required, name='dispatch')

これってログインさせるためのものだと思うのですが、↲すぐ後ろこclassにかかっているってことで合っていますか？

**Comment by ernix** [comment]
これはPythonのデコレータと呼ばれる構文で、糖衣構文の一種です。
http://note.crohaco.net/2014/python-decorator/

デコレータには関数デコレータとクラスデコレータの二種類があり、
関数デコレータは"関数を引数にして関数を返す関数"として定義されており、
クラスデコレータは"クラスを引数にして関数を返す関数"として定義されています。

```python
@method_decorator(login_required, name='dispatch')
class GroupCreate(CreateView):
    ...
```

というのは単に以下のコードと全く同じで、
クラスの振る舞いをデコレータによって変更できるようになっています。

```python
class GroupCreate(CreateView):
    ...

GroupCreate = method_decorator(login_required, name='dispatch')(GroupCreate)
```

Djangoではいくつかのデコレータが定義されていて、
ビュークラスを修飾することでビューの属性を変更させることができるようになっています。
https://docs.djangoproject.com/en/1.11/topics/class-based-views/intro/
