### ISSUE TITLE
新規ボランティア作成フォーム　上限人数　ゼロ除算

### ISSUE THREAD

**Issue by flower-pepper** [internship2016/sovolo#280]
url:sovol.earth/event/add/

エラーが出る箇所
/home/docker/code/app/event/models.py in get_filled_rate, line 195

新規ボランティア作成フォームで上限人数を0にすると
ゼロ除算でエラーになるので、フロントエンドで上限人数を設定する場合は1人以上しか設定できないようにして、サーバーサイドでは、再入力を促す画面を返すように改善したい。

何より、新規作成でdjangoのエラーページが出るのに、ボランティア一覧に追加されてしまうのがよくない。一覧からボランティア詳細に飛ぶと、djangoのエラーページが表示される。
データベースに追加してしまう前に内容をチェックするべき。

**Comment by ernix** [comment]
取り急ぎ、ゼロ除算に関するエラーを取り除きました。
0のような応募数は常識的に考えてありえないですが、モデルが許容している以上それを尊重する形です。
ゼロ除算による応募割合を100とするのが適当かは、検討の余地があります。

https://github.com/internship2016/sovolo/commit/22d0c67a05e7d2064423635b4ccfaef2c4393d40
