### ISSUE TITLE
Let's encryptによる証明書更新を自動化したい

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#281]
cronジョブなどに登録して自動化させたいが、スタンドアロンで動かす場合
80番ポートを使うnginxが邪魔で逐次nginxを止める必要があった。
これをstaticなエンドポイントに変更するなどしてnginxを止めなくても自動的に証明書を更新させたい。

**Comment by MURAKOSHITAKAHIRO** [comment]
まだ、終わっていない案件なのでこのままにします。

私個人の意見としては2018年中に終わらせたい。

**Comment by ernix** [comment]
現在の更新方法だとダウンタイムが発生するので、それをなくす改善提案。

**Comment by ernix** [comment]
done
https://github.com/internship2016/sovolo/commit/0a1f7e70068c20565e8c336359d53c2210e7033e
