### ISSUE TITLE
dotenvのワーニング

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#283]
起動される度に以下のワーニングが出る。
System check identified no issues (0 silenced).
August 11, 2017 - 05:56:44
Django version 1.11.4, using settings 'sovolo.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
/usr/local/lib/python3.4/dist-packages/dotenv.py:56: UserWarning: Not reading /home/docker/code/app/.env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))

**Comment by ernix** [comment]
appの直下に.envファイルを作ってください。 `touch .env`
.envは.gitignoreによってコミットされないファイルに指定されています。

**Comment by haraguchijouji** [comment]
/home/docker/code/appの下に空のファイル.envを置く
$ touch .env
