### ISSUE TITLE
募集作成時の地図指定がいきなりは出来ない

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#289]
ピンボタンクリック時に「緯度経度情報を取得できませんでした。」

**Comment by ernix** [comment]
ピンボタンをクリックする前に目印となるキーワードを入力してもらえますか？

**Comment by haraguchijouji** [comment]
いきなり地図から場所指定ができないものか・・・
最初の緯度経度はGPS情報にアクセスして広域地図を表示しておく--->地図上でピンを移動して、指定。

**Comment by MURAKOSHITAKAHIRO** [comment]
修正をお願いいたします。

**Comment by ernix** [comment]
UIに関するぎこちなさの修正。確かに分かりづらいが意図通りの動きをしている。

**Comment by MURAKOSHITAKAHIRO** [comment]
現時点ではできているので、閉じます。
