### ISSUE TITLE
タイトル長に制限がなく、表示が重なったりボタンがガタガタになったり

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#293]
<img width="593" alt="screen shot 2017-08-16 at 17 29 46" src="https://user-images.githubusercontent.com/343556/29390975-c208a8a0-82a8-11e7-909f-158e0d126048.png">

**Comment by scirocco0316** [comment]
現在 20 文字までという制限があるようですが、20 文字って結構短いので、作成時に制限するのではなく、表示時に "..." で省略するような方がよいのではないでしょうか？
