### ISSUE TITLE
終了したボランティアが「地域の新着ボランティア」検索で表示される。

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#294]
REV:95ecf60
![image](https://user-images.githubusercontent.com/8582641/29427345-7c130116-83c4-11e7-9790-e388220e70a2.png)

**Comment by flower-pepper** [comment]
修正しました
https://github.com/internship2016/sovolo/commit/4693130517f7c841a414808603717a388b5a5747

**Comment by haraguchijouji** [comment]
確認しました。
REV:42349d7
![image](https://user-images.githubusercontent.com/8582641/29436817-78f79446-83e8-11e7-965e-3ebb764ac3f8.png)
