### ISSUE TITLE
トップページの画像がおもすぎる

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#297]
✔ kojima:skmbp ~$ curl --head 'http://localhost:8000/static/img/topimg.jpg'
HTTP/1.0 200 OK
Date: Fri, 18 Aug 2017 17:28:34 GMT
Server: WSGIServer/0.2 CPython/3.4.3
Content-Type: image/jpeg
Last-Modified: Thu, 17 Aug 2017 00:27:40 GMT
Content-Length: 37405505

さすがに画像一枚37Mはやり過ぎ。ターゲットを定めて適切に縮小する必要がある。

**Comment by MURAKOSHITAKAHIRO** [comment]
確かに重いです。
何か対策を提案したいと思います。

**Comment by ernix** [comment]
あと今気づいたけど、ウィンドウ幅によって画像のアスペクト比が変わるのはいただけない。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
画像を軽くする方法はありますか。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO 軽くしました。 https://github.com/internship2016/sovolo/commit/c4e98e0b2b5eef6f14cc231bbe9901ecd57e51f9
36M => 653k
