### ISSUE TITLE
コメントが入力できない

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#298]
1. ボランティアを選択
2. コメント蘭に入力
3. 「私はロボットではありません」にチェック
4. 「送信」ボタンをクリック
5. 「認証に失敗しました」と出る
![image](https://user-images.githubusercontent.com/8582641/29472834-5093dfe8-8490-11e7-8f8e-5eb3f40b5893.png)

**Comment by ernix** [comment]
dup: https://github.com/internship2016/sovolo/issues/330

**Comment by MURAKOSHITAKAHIRO** [comment]
コメントを入力することが出来ました。
OKです。
