### ISSUE TITLE
プロフィールの画像の設定がうまくいかない。

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#299]
「プロフィール編集」ボタンをクリック
「プロフィール画像」選択--->画像を選択して「開く」
（プロフィール画像が表示される。画像ファイル名が表示される。）
「適用」ボタンをクリック
「プロフィール編集」画面のまま
（プロフィール画像がない。画像ファイル名が空欄。）

**Comment by ernix** [comment]
JavaScriptのFormDataオブジェクトがうまく行ってないっぽいです。

ブラウザ上でアップロードされた画像の部分切り出しを行うのに[croppie.js](https://github.com/Foliotek/Croppie)を使ってるんですが、こいつが切り取れるデータ形式がbase64で、切り取った画像を無理やり上書き(単純に画面遷移でPOSTするのではなくajaxでPOST)するのにBlobオブジェクトをappendしたFormDataオブジェクトを使っています。

どうもこの際ajaxでPOSTしたフォームにBlobオブジェクトが含まれてる感じがしません。
前まではうまく動いてたんだけどなぁ。うーん。

**Comment by haraguchijouji** [comment]
正常動作を確認

**Comment by MURAKOSHITAKAHIRO** [comment]
プロフィールの画像の設定が出来ることを確認しました。
