### ISSUE TITLE
カレンダーで探す」の検索結果に何も表示されてないブロックが出る。

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#300]
検索結果ブロックとカレンダーブロックとの間
![image](https://user-images.githubusercontent.com/8582641/29531688-8839ec48-86e4-11e7-8d85-fc04c8817f0a.png)

**Comment by haraguchijouji** [comment]
rev: 7d3353c
現在は四角の１が出ます。
![image](https://user-images.githubusercontent.com/8582641/29629795-fd9a2296-8874-11e7-8b41-9a5ab0f5e3bb.png)

**Comment by haraguchijouji** [comment]
1ページしかない場合はページブロックは無くても良いのではないか。

**Comment by MURAKOSHITAKAHIRO** [comment]
ページ数を表示するは問題ないと思いますので、
閉じます。
