### ISSUE TITLE
トップページが「English」ボタンが日本語にならない

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#301]
「プロフィール編集」で使用言語を「English」を選択するとトップページに「English」ボタンが出るが、
「日本語」にしようと思ってもどこからも変更できない。

![image](https://user-images.githubusercontent.com/8582641/29541170-5e3836e2-870d-11e7-9499-e6d779bf13b0.png)

**Comment by hejob** [comment]
調査しましたが、ボタン自体はないらしいです。すでに解決しているのでしょうか。

**Comment by haraguchijouji** [comment]
ログイン前の状態ではボタンがあります。
ただし、現在は修正済みと思われます。
rev: 380f892

**Comment by haraguchijouji** [comment]
ログイン後はプロフィール修正で言語選択を変更してトップページを表示させると正常に表示されます。

**Comment by MURAKOSHITAKAHIRO** [comment]
修正を確認しました。
