### ISSUE TITLE
トップのスワイプ部分のイベントに「終了」したものも表示されている。

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#302]
「募集中」「募集終了」「イベント終了」の区別がスワイプ部分だけで解るようにして欲しい。
「イベント終了」-->表示されない
「募集終了」-->募集終了アイコン（または文字）を同時表示
「募集中」-->現在の表示

**Comment by haraguchijouji** [comment]
「イベント終了」-->表示されない --> 確認　済

**Comment by MURAKOSHITAKAHIRO** [comment]
いったん閉じます。
