### ISSUE TITLE
複数のタグで絞り込みを行うと同じイベントが複数出てくる

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#303]
２個のタグにチェックした結果
![image](https://user-images.githubusercontent.com/8582641/29575110-843c5698-879e-11e7-928e-67940457e1ce.png)

**Comment by haraguchijouji** [comment]
rev: 7d3353c
出ないことを確認しました。

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
