### ISSUE TITLE
calenderのsearch resultの画面がおかしい

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#304]
募集中などの表記が日本語。
![image](https://user-images.githubusercontent.com/8582641/29581228-9fe31048-87b3-11e7-8b82-e68664d3bdb5.png)

「search」ボタンが切れている
![image](https://user-images.githubusercontent.com/8582641/29581292-bfac7cfc-87b3-11e7-8227-0005be7b4285.png)

**Comment by haraguchijouji** [comment]
browseでは募集中などが英語で表記できている。
![image](https://user-images.githubusercontent.com/8582641/29581473-5829f702-87b4-11e7-8780-dcdea6a05598.png)

**Comment by haraguchijouji** [comment]
「Wanted」で「管理者」なイベントの表示がbrowseやmapでは「Wanted」、calenderでは「管理者」と表示される。
![image](https://user-images.githubusercontent.com/8582641/29588591-1c1b1228-87cd-11e7-9d6e-7f9eb56d9346.png)

**Comment by haraguchijouji** [comment]
rev: 7d3353c
Searchのボタンが切れている件は治っているのを確認

**Comment by hejob** [comment]
前のボタンが違ったりするのは確認できました。
修正しましたが、PR作るには別のブランチを立つ必要があるようです。マージに一番やりやすい方法は何でしょうか。

**Comment by haraguchijouji** [comment]
@ernix 
黄君への指示お願いします。

**Comment by ernix** [comment]
ブランチ切ってP-r投げて下さい

**Comment by haraguchijouji** [comment]
＞募集中などの表記が日本語。
＞「Wanted」で「管理者」なイベントの表示がbrowseやmapでは「Wanted」、calenderでは「管理者」と表示される。
上記2点について修正されているのを確認しました。

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
