### ISSUE TITLE
event listでは日時が日本語表記だがdetailでは英語表記になっている

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#305]
detailの画像
![image](https://user-images.githubusercontent.com/8582641/29581868-ae26134c-87b5-11e7-97a4-c01629c8ab75.png)

event listの画像
![image](https://user-images.githubusercontent.com/8582641/29581926-dc5ea49a-87b5-11e7-9bee-a269b3905991.png)

**Comment by hejob** [comment]
調査しましたが、問題はないらしいです。すでに解決しているのでしょうか。

**Comment by haraguchijouji** [comment]
@hejob 
確認しました。
解決している模様です。
![default](https://user-images.githubusercontent.com/8582641/34974552-0a5e9dc6-fad1-11e7-82ba-39fb0ab5a456.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
