### ISSUE TITLE
[イベント作成] 手入力すると開始日より前の終了日を指定しても、そのままイベントが作成されてしまう

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#306]
![2017-08-23 06 29 37](https://user-images.githubusercontent.com/13220375/29588472-a24c2158-87cc-11e7-98fb-d3fdb1846261.png)

**Comment by haraguchijouji** [comment]
入力画面で指定不可になっています

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
