### ISSUE TITLE
[イベント作成] 地図でピンを置いた場所に合わせて Location を変更できないか

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#307]
現状だと、地図でピンを置いても Location が自動で変わるようになっていないので、ピンを置いたのが東京なのに Location が北海道とかでイベントが作成できてしまいます。

![2017-08-23 06 41 42](https://user-images.githubusercontent.com/13220375/29588997-89a5c850-87ce-11e7-9f53-47c76c41d9e9.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
修正されているので、閉じます。
