### ISSUE TITLE
プロフィール画面の表示がおかしい

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#308]
トロフィーのブロックタイトルの部分の矢印だけ下向きになっている。
![image](https://user-images.githubusercontent.com/8582641/29721927-cd9cea3e-89f9-11e7-8bbf-ad80464e8ccc.png)

**Comment by haraguchijouji** [comment]
向きの修正を確認
rev: 9ad6554
![image](https://user-images.githubusercontent.com/8582641/29724718-7fae4088-8a04-11e7-8689-4db51b103a5e.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
