### ISSUE TITLE
[ユーザー登録] ボタンをクリックした後、エラー画面になってしまう

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#309]
![2017-08-26 05 29 20](https://user-images.githubusercontent.com/13220375/29731627-02231ac8-8a20-11e7-80eb-36caef646401.png)

**Comment by haraguchijouji** [comment]
新規ユーザーの登録は正常にできることを確認。
rev: 380f892

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
