### ISSUE TITLE
[パスワード再設定]  謎の数字が表示される

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#310]
"パスワードを再設定したいメールアドレスを入力してください" というメッセージの左に "8" という数字が表示されます。
![2017-08-26 05 37 21](https://user-images.githubusercontent.com/13220375/29731806-dc2b669e-8a20-11e7-88d5-ca8bb44e0efc.png)

**Comment by haraguchijouji** [comment]
修正されているのを確認。
rev: 380f892

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
