### ISSUE TITLE
[コメント投稿] "認証に失敗しました。" というエラーが出る

### ISSUE THREAD

**Issue by scirocco0316** [internship2016/sovolo#311]
自分の作ったイベントにコメントを投稿しようとしたところ、"認証に失敗しました。" というエラーになりました。

![2017-08-26 05 57 15](https://user-images.githubusercontent.com/13220375/29732440-9770f020-8a23-11e7-84a2-a189ed1f50bc.png)

**Comment by haraguchijouji** [comment]
正常にコメントが入力できることを確認。
rev: 380f892

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
