### ISSUE TITLE
ボランティアの用語が統一されていない

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#314]
以下のようにしたらどうでしょう。
「ボランティアを検索」 --> ボランティア活動（volunteer activities）を探す
「ボランティア作成」 --> ボランティア活動（volunteer activities）を作る
「ボランティアを探す」 --> ボランティア活動（volunteer activities）を探す
「人を探す」 --> ボランティア（volunteer）を探す

**Comment by haraguchijouji** [comment]
「ボランティアをはじめる」 --> ボランティア活動（volunteer activity）をはじめる

**Comment by haraguchijouji** [comment]
「ボランティアをはじめる」 --> ボランティア活動（volunteer activity）をはじめる
「ボランティア名」 --> ボランティア活動名
「ボランティア画像」 --> 参考画像
「仕事内容」 --> 活動内容
「ボランティア検索」 --> ボランティア活動（volunteer activities）を探す
「締め切られたボランティアを除外 」 --> 締め切られたボランティア活動を除外
「満員になったボランティアを除外」 --> 満員になったボランティア活動を除外
「管理しているボランティア一覧」 --> 管理しているボランティア活動一覧
「参加予定のボランティア一覧」 --> 参加予定のボランティア活動一覧
「ボランティア実績」 --> ボランティア活動実績

**Comment by haraguchijouji** [comment]
統一済
rev: 5899c2f

**Comment by MURAKOSHITAKAHIRO** [comment]
閉じます。
