### ISSUE TITLE
プロフィール編集ボタンの文字の色が変

### ISSUE THREAD

**Issue by tasugi** [internship2016/sovolo#32]
ユーザー編集画面からリンクがある、プロフィール編集ボタンの文字の色が見にくい

**Comment by ernix** [comment]
パネルのヘッダの上にボタンがあるから、白字になってる。
形としてはパネルのボディ側にボタンがあるのが正しいようにも思うけど・・・ヘッダの上？

**Comment by tasugi** [comment]
ボタンの位置を変更することで対応しました
