### ISSUE TITLE
facebookログインでログインID部分に日本語コードらしきものが表示される

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#320]
facebookログインID：原口譲治
表示されたコード：c88ba984178e4239

**Comment by haraguchijouji** [comment]
原因の追究はpriority high

**Comment by hejob** [comment]
ユーザーネームの後ろにランダムコードが追加される現象は、コード上で確認しました。
登録する時、facebookのユーザーネームがシステム内ですでに登録された場合、後ろにランダムのコードを追加する模様です。

**Comment by hejob** [comment]
調査中では、本件と関係しているバグが発見されました。
FacebookのEmailがすでに登録された場合、エラーになります。Twitterと同様に修正を試して見ましたが、Authプラグインの内部処理方法が違うらしく、治らない模様です。プラグイン自体の修正になる可能性があります。

**Comment by haraguchijouji** [comment]
上記了解しました。
原因追究としては一旦後回しにしてください。
プラグイン自体の修正を行うかどうかは後程決定します。

**Comment by MURAKOSHITAKAHIRO** [comment]
SNS(Twitter/Facebook)の連携 #338

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
消えていますので、クローズします。
![snapcrab_noname_2018-5-22_17-29-46_no-00](https://user-images.githubusercontent.com/34121151/40350810-ce11468e-5de5-11e8-94c4-0ed0df2cf66c.png)
