### ISSUE TITLE
トップページのスライダー部分の文字がぼけてるように見える

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#321]
![default](https://user-images.githubusercontent.com/8582641/30140612-d2ce5ff4-93b0-11e7-8b10-dc116c103531.png)

**Comment by ernix** [comment]
ううーん・・・・確かに。WindowsのChromeですか？

**Comment by haraguchijouji** [comment]
そうです。

**Comment by haraguchijouji** [comment]
現状大丈夫になっているようです。
2018 1/16

**Comment by haraguchijouji** [comment]
現状多少ましになっているようです。
2018 1/16
![_](https://user-images.githubusercontent.com/8582641/34973217-eaa281f2-fac9-11e7-87fd-74799e0d8ce9.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しましたが、ぼけているように見えなかったので閉じます。
