### ISSUE TITLE
プロダクション環境でadminページのCSSが見つからない

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#322]
settings.py に STATIC_ROOT の設定がなく、 `python3 manage.py collectstatic` が使えない。

本来 collectstatic によって配置されるはずの各種assetがgulpとの絡みでstaticディレクトリに直書きになっているので、admin用のcssを追加しようとすると同じディレクトリ間でコピーしようとしてエラーが発生する模様。

**Comment by hejob** [comment]
調査しましたが、問題はないらしいです。すでに解決しているのでしょうか。

**Comment by haraguchijouji** [comment]
@ernix 
確認できますか？

**Comment by ernix** [comment]
sovol.moe の方は無理やり `sovolo/app/static/admin` ディレクトリを作り、`python3 manage.py collectstatic`によって作成されるadmin用のassetを手動でコピーしました。
本issueの本題は、「cssが見つからない」という問題ではなく、djangoと`sovolo/app/gulpfile.js`をどのように同居させるべきかという問題の解決を求めるものです。

**Comment by ernix** [comment]
collectstaticでassetを作ろうとするとsovolが必要とするBootstrap等のプリプロセスが出来ず、gulpでやるとadminページが必要とするアセットが作られない、という。

**Comment by ernix** [comment]
解決方法の一つは、今のようにgulpで全部アセットを用意するのではなく、
Django流のcollectstaticからgulpをフックする方法に変更することです。

使ったこと無いけど以下のパッケージはこの問題を解決しようとしている:
https://github.com/beaugunderson/django-gulp
