### ISSUE TITLE
Edge、Chromeにおいて、Twitterアカウントでログインできない

### ISSUE THREAD

**Issue by il-ma-takahashi** [internship2016/sovolo#324]
【改修希望】
MicrosoftEdge、Chromeにおいて、Twitterアカウントでログインできない。不具合を改修願います。

【状況】
MicrosoftEdge、ChromeでTwitterアカウントよりログインを試みると、
添付ファイルのようなコードが表示されて、ログイン完了に至りません。

(Firefox、Safariにおいては、Twitterアカウントでも問題なくログインできました。)

![snapcrab_noname_2017-11-30_9-12-24_no-00](https://user-images.githubusercontent.com/34120004/33416511-508471f6-d5e0-11e7-9464-274880b8ee37.png)

![snapcrab_noname_2017-11-30_9-18-24_no-00](https://user-images.githubusercontent.com/34120004/33416512-53174c9a-d5e0-11e7-9b6a-c7fa4c28b1ca.png)

**Comment by ernix** [comment]
@il-ma-takahashi 既に登録されているemailで試そうとしませんでしたか？
全く新しいemailアドレスでも同様の問題が発生しますか？

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
修正されています。
