### ISSUE TITLE
Sovol Twitterアカウント登録時のエラーが発生

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#325]
【バグfix】優先度：最優先
Chrome、Edge、Firefox、Safariにおいて、メールアドレス登録済みのユーザーが、
Twitterアカウントでログインできない不具合を改修願います。新規メールアドレス登録は問題なし。

【状況】
「Twitterアカウントでログイン」する際は、Eメールアドレスの登録が必須とされています。

登録済のユーザーが、Twitterアカウントでログインを試みると、
添付ファイルのようなコードが表示されて、ログイン完了に至りません。

■Chrome
![snapcrab_noname_2017-11-30_9-12-24_no-00](https://user-images.githubusercontent.com/34121151/33418783-db1ba9ec-d5ea-11e7-82a9-e98fdb1f6a3c.png)

■Edge
![snapcrab_noname_2017-11-30_9-18-24_no-00](https://user-images.githubusercontent.com/34121151/33418784-db3f8f38-d5ea-11e7-8df7-32af5d7d0550.png)

■Firefox
![snapcrab_noname_2017-11-30_15-48-13_no-00](https://user-images.githubusercontent.com/34121151/33418807-f72197aa-d5ea-11e7-8c85-cc7a146ef325.png)

**Comment by hejob** [comment]
エラーの調査ですが。
【原因】Twitterログインした後、ユーザEMAILを入力できますが、既存ユーザのEMAILを入力すると、確認せずにユーザ作成するので、エラーになります。
【修正仕様】既存ユーザの影響はできないので、EMAILが衝突する場合、エラーメッセージを表示して、再度入力画面に戻るのかいいのではと、その場合のエラーメッセージなどが必要です。

**Comment by hejob** [comment]
ソースからついでの発見ですが。

【バグ】Twitterログインした後、Twitterアカウント名と同じユーザを作成しようとしますので、既存ユーザ名ですと同じくエラーになると予想します。

**Comment by ernix** [comment]
@haraguchijouji エラーメッセージどうしましょうか？取り急ぎ↓の文章でお願いしてもらうのがいいかと思いますが。
「すでにアカウントが存在しています。お手数ですが他のアカウントでご利用下さい。」

**Comment by haraguchijouji** [comment]
@ernix エラーの調査結果についてのメッセージではこのメッセージで良いと思います。

**Comment by haraguchijouji** [comment]
@hejob 【バグ】Twitterログインした後、Twitterアカウント名と同じユーザを作成しようとしますので、既存ユーザ名ですと同じくエラーになると予想します。

これについては「Twitterログインした後、」に「Twitterアカウント名と同じユーザを作成」しないと
何か不都合が生じるのでその様にした訳では無いと云うことが明確であれば「Twitterアカウント名と同じユーザを作成」部分を削除することで良いと考えます。

**Comment by MURAKOSHITAKAHIRO** [comment]
■SNS(Twitter/Facebook)の連携 · Issue #338 · internship2016/sovolo
https://github.com/internship2016/sovolo/issues/338

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
エラーメッセージが出ていますのでこの件はクローズします。
![snapcrab_noname_2018-5-22_17-10-11_no-00](https://user-images.githubusercontent.com/34121151/40349952-2c88b06a-5de3-11e8-940a-ae87188247e2.png)
