### ISSUE TITLE
SOVOLのボランティア募集ページのコメント欄に書き込みが出来ない。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#330]
Sovolのコメント欄の認証がエラーを起こしているために書き込みが出来ない。
![snapcrab_noname_2018-2-16_17-43-58_no-00](https://user-images.githubusercontent.com/34121151/36299848-37eeb788-1342-11e8-82b5-fb40cf775da4.png)

**Comment by ernix** [comment]
取り急ぎキーを用意して修正しました。このissueは一旦closeせずにおいておいてもらえますか。
![screen shot 2018-02-16 at 18 17 38](https://user-images.githubusercontent.com/343556/36300761-c51f34ea-1345-11e8-9e2b-883b3d47bb95.png)

@hejob コードに問題があります。コードビューにコメントを書くので確認してください。

**Comment by MURAKOSHITAKAHIRO** [comment]
わかりました。
お願いいたします。

**Comment by MURAKOSHITAKAHIRO** [comment]
@Shin Kojima
修正ありがとうございます。

**Comment by ernix** [comment]
https://github.com/internship2016/sovolo/commit/ddf33914d91c367606396bf3a3137da79c72e6a6
変更をmasterに入れたのでクローズします。

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました
