### ISSUE TITLE
Twitterアカウントでログイン時に、OAuthをキャンセルするとスタックトレースが出現する

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#331]
Twitterアカウント登録で「Sovol.moeにアカウントの利用許可をしますか。」という質問で、
「許可しない」とクリックした後に、「Sovol.moeに戻る」をクリックするとコードが出現してしまいます。
![snapcrab_noname_2018-2-19_14-24-18_no-00](https://user-images.githubusercontent.com/34121151/36363653-0ad63ffe-1582-11e8-9b50-3dc1f79d4391.png)
![snapcrab_noname_2018-2-19_14-24-47_no-00](https://user-images.githubusercontent.com/34121151/36363656-0d4cf912-1582-11e8-9041-f34d8c53ce6d.png)
![snapcrab_noname_2018-2-19_14-23-56_no-00](https://user-images.githubusercontent.com/34121151/36363659-1033683c-1582-11e8-838f-03d3f2263732.png)

**Comment by ernix** [comment]
確認しました。エラー画面の未実装によるものです。

    Exception Value: | Authentication process canceled

**Comment by MURAKOSHITAKAHIRO** [comment]
ありがとうございます。
おそらくFacebookアカウントでも同じことが発生すると思います。
確認はしておりませんが。

**Comment by ernix** [comment]
テクニカルな実害は無いが、見た目が酷いという意味で深刻。

**Comment by MURAKOSHITAKAHIRO** [comment]
■SNS(Twitter/Facebook)の連携 · Issue #338 · internship2016/sovolo
https://github.com/internship2016/sovolo/issues/338

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob 　違うページに飛ぶようになっていますが、新たな問題が発生しているので、
以下でまた、話し合います。
「sovol.moeに戻る」をクリックするとメールアドレス登録画面に移動する。 #340
