### ISSUE TITLE
Sovolの登録メールがGmailでスパム扱いになっている。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#333]
Sovol登録メールがGmailでは迷惑メールに入ってしまう。
解除できるでしょうか。
![snapcrab_noname_2018-4-5_9-30-29_no-00](https://user-images.githubusercontent.com/34121151/38341670-b8520d48-38b4-11e8-9d1e-ba4f3fc3d9e7.png)

**Comment by ernix** [comment]
そもそも、なにゆえsovol.moeのサービスでsovol.earthから送られているのか・・・
ハードコードになっているところを修正してみます。

**Comment by ernix** [comment]
@hejob ドメイン名がハードコードになっているので、envに出せないかちょっと見ていただけますか？
https://github.com/internship2016/sovolo/commit/30d3d4d9e03f5759aeea1b8628dd075d01b9c470

@MURAKOSHITAKAHIRO 
コードを変更して再起動かけたので、もう一度試してみてください。

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しましたが、だめのようです。
![snapcrab_noname_2018-4-5_11-44-53_no-00](https://user-images.githubusercontent.com/34121151/38344870-d4416c6c-38c6-11e8-8a7c-92447781aea8.png)

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO すみません、サービスがうまく再起動できてなかったみたいです。
再起動後メールがIPv6優先になっていたので、システムレベルでv6を切りました。

/etc/sysctl.conf
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

```
sudo sysctl -p
```

**Comment by MURAKOSHITAKAHIRO** [comment]
新しいアカウントで確認しましたが、迷惑メール扱いのままです。
![snapcrab_noname_2018-4-9_17-44-39_no-00](https://user-images.githubusercontent.com/34121151/38488281-ebf78c24-3c1d-11e8-9524-48bc1b03bac0.png)

**Comment by ernix** [comment]
優先度上げましたが、コード上の修正ではなくむしろ運用上の問題になります。

**Comment by MURAKOSHITAKAHIRO** [comment]
了解です

**Comment by MURAKOSHITAKAHIRO** [comment]
kojimaにこの件を一任してもいいでしょうか。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO sovol.moeにDKIM設定しました。確認してもらえますか？

**Comment by MURAKOSHITAKAHIRO** [comment]
確認しました。
4月17日にGmailアドレスで登録を行ったところ、
以下のメールが送信されていました。
問題ないと思います。

![snapcrab_noname_2018-4-18_9-20-6_no-00](https://user-images.githubusercontent.com/34121151/38905159-c1eb16ee-42e9-11e8-81ca-e91cdc5ace47.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
質問ですが、
登録確認メールが届いてから放置すると登録が削除されるといった機能はありますか。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO 
別のissueとして登録しました。
https://github.com/internship2016/sovolo/issues/336

**Comment by MURAKOSHITAKAHIRO** [comment]
それではここは閉じます。
