### ISSUE TITLE
Facebookアカウントでログインすると、ユーザ名が"b8326b7f514a415a"のようになる

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#334]
Facebookアカウントで登録した際に以下のおかしなUserNameになります。
ちゃんとしたFacebookアカウントのUserNameになりませんか。
![snapcrab_noname_2018-4-18_10-51-11_no-00](https://user-images.githubusercontent.com/34121151/38907918-f2f1d660-42f8-11e8-8f42-6a5aaba14278.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
■SNS(Twitter/Facebook)の連携 · Issue #338 · internship2016/sovolo
https://github.com/internship2016/sovolo/issues/338

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob @ernix
まだ、「b1760f1b1f334970 」と出てくる。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO 
このチケットはまだOpenですが、何をもって「もう出てこないはず」と判断されましたか？

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
こちらのミスです。
#338に統合しようとしてCloseしてしまいました。
その後、統合できないことがわかったため、Openにしました。
申し訳ございません。

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob @ernix 
Facebookアカウントで登録する際に以下の表示が出て来ましたので、
クローズします。

<img width="1627" alt="2018-06-26 13 11 29" src="https://user-images.githubusercontent.com/34121151/41891349-e034fef8-794e-11e8-8a78-4a24b323ace1.png">
