### ISSUE TITLE
すでにsovolに登録されているメールアカウントを持つFacebookアカウントでログインするとdjangoのスタックトレースが現れる

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#335]
Facebookアカウントで登録しようとした際に、
先にFacebookアカウントのメールアドレスをと同じメールアドレスが登録されていた場合、
コードが出現してしまいます。

おそらくは重複してしまうためエラーになっていると思うのですが、
エラーページがないのが原因だと思われます。
エラーページを作成していただけますでしょうか。

**Comment by ernix** [comment]
原因はこれと同じだと考えます: https://github.com/internship2016/sovolo/issues/325

**Comment by MURAKOSHITAKAHIRO** [comment]
私も思います。
 #325が解決したらこちらにも適用していただきますか。

**Comment by MURAKOSHITAKAHIRO** [comment]
SNS(Twitter/Facebook)の連携 #338

**Comment by MURAKOSHITAKAHIRO** [comment]
■SNS(Twitter/Facebook)の連携 · Issue #338 · internship2016/sovolo
https://github.com/internship2016/sovolo/issues/338

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob @ernix 
まだ、「b1760f1b1f334970 」と出てくる。

**Comment by MURAKOSHITAKAHIRO** [comment]
テストした結果
![snapcrab_noname_2018-6-5_10-45-59_no-00](https://user-images.githubusercontent.com/34121151/40950445-be48df0a-68ad-11e8-8aa0-a41d4ead4f67.png)
