### ISSUE TITLE
参加枠と上限の表現が矛盾している

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#337]
@hejob これってバグかな？
![screen shot 2018-05-21 at 17 29 47](https://user-images.githubusercontent.com/343556/40298111-e75350a2-5d1c-11e8-98f4-aef86868b25d.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob  調査を御願いします。

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob 
「参加枠１」の「１」を表示させないようにしてください。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 

修正されているのが確認されましたので、Closeします。
<img width="1051" alt="2018-06-22 17 42 23" src="https://user-images.githubusercontent.com/34121151/41767102-b9be64e8-7643-11e8-8f3f-07a9b642c609.png">
