### ISSUE TITLE
SNS(Twitter/Facebook)の連携

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#338]
SNSの連携が出来ていないため、
以下のフローチャートを元に作成してください。

```
### SNS連携のフローチャート

- Twitter/Facebook連携
    1. フォームの表示
        * アカウント名/メールアドレスのデフォルト値をSNSと同じに。
        * SNSに情報が無ければその欄は空
        * アカウント重複ならsuffixにランダム数字
    2. フォーム送信
        * 成功ならそのままログイン
        * 入力データ不備、もしくはエッジケースでフォームの表示から送信の間に
          重複アカウントが登録されてしまった場合はエラーを出してフォーム再入力を促す。
```

**Comment by MURAKOSHITAKAHIRO** [comment]
### SNS連携のフローチャート
#### Twitter/Facebook連携
    1. フォームの表示
        * アカウント名/メールアドレスのデフォルト値をSNSと同じに。
        * SNSに情報が無ければその欄は空
        * アカウント重複ならsuffixにランダム数字
        * 戻るをクリックした場合はホーム画面に戻る。
    2. フォーム送信
        * 成功ならそのままログイン
        * 入力データ不備、もしくはエッジケースでフォームの表示から送信の間に
          重複アカウントが登録されてしまった場合はエラーを出してフォーム再入力を促す。

**Comment by MURAKOSHITAKAHIRO** [comment]
Facebookアカウント登録　成功
Twitterアカウント登録　　失敗

以下が失敗した際のエラー
![snapcrab_noname_2018-5-22_13-44-33_no-00](https://user-images.githubusercontent.com/34121151/40342781-9253d86e-5dc7-11e8-857c-70757066754b.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
もう少しこちらでも調べます。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO 
コード変更時にデータベースがアップデートされていなかったのが原因みたいです。
もう一度確認してもらえますか？

```
# python3.6 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, event, sessions, social_django, tag, user
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
```

**Comment by MURAKOSHITAKAHIRO** [comment]
登録できることを確認しました。
![snapcrab_noname_2018-5-22_15-55-33_no-00](https://user-images.githubusercontent.com/34121151/40346743-be111e2e-5dd8-11e8-8798-bac7aef7ba0a.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
Twitter で登録する際に「sovol.moeに戻る」をクリックするとE-mailアドレス登録にいってしまう。
![snapcrab_noname_2018-5-22_16-11-39_no-00](https://user-images.githubusercontent.com/34121151/40347418-2f600da4-5ddb-11e8-962f-4ead09be0bcc.png)
![snapcrab_noname_2018-5-22_16-11-13_no-00](https://user-images.githubusercontent.com/34121151/40347429-384686a0-5ddb-11e8-8f15-b325a3ceba26.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
Twitter で登録する際に「sovol.moeに戻る」をクリックするとE-mailアドレス登録にいってしまう問題は以下の番号で話し合います。
「sovol.moeに戻る」をクリックするとメールアドレス登録画面に移動する。 #340

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
Facebookアカウントでログインしようとすると管理者「muran」でログインしてしまうのはどうしてでしょう。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
新しく以下に変更します。

* 現在のSNS連携のフローチャート

+----------+     +----------+     +--------+  no   +------+
| 登録開始 | --> | ログイン | --> | 重複？ | ----> | 登録 |
+----------+     +----------+     +--------+       +------+
                                    |                 A
                                    | yes             |
                                    v                 |
                                  +----------------------+
                                  | 異なる値を入力させる |
                                  +----------------------+


* 新しいSNS連携のフローチャート

+----------+     +----------+     +--------+  no   +--------------------+       +------+
| 登録開始 | --> | ログイン | --> | 重複？ | ----> | 確認メールを飛ばす | ----> | 登録 |
+----------+     +----------+     +--------+       +--------------------+       +------+
                                    |                  A
                                    | yes              |
                                    v                  |
                                  +-----------------------+
                                  | 通常登録へ            |
                                  +-----------------------+

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
SNS連携のフローチャートを以下のように変更します。

<img width="581" alt="2018-06-27 17 34 57" src="https://user-images.githubusercontent.com/34121151/41962659-8b0b0e3a-7a30-11e8-9ffa-177501053038.png">

**Comment by MURAKOSHITAKAHIRO** [comment]
通常登録というのはこの画面のことです。

https://sovol.moe/user/register/

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
@hejob 
一通りできているようなので、closeします。
