### ISSUE TITLE
「sovol.moeに戻る」をクリックするとメールアドレス登録画面に移動する。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#340]
Twitter登録画面で「ＣＬＥＡＲ」をクリックして、次に「sovol.moeに戻る」をクリックするとメールアドレス登録画面に移動する。
![snapcrab_noname_2018-5-22_16-11-39_no-00](https://user-images.githubusercontent.com/34121151/40348222-f4b0e7b6-5ddd-11e8-9204-be9c9624bff7.png)
![snapcrab_noname_2018-5-22_16-11-13_no-00](https://user-images.githubusercontent.com/34121151/40348224-f6dc7df2-5ddd-11e8-81a8-a023d94892d3.png)

**Comment by ernix** [comment]
@hejob twitterでログインできていないのにユーザ登録の画面に進んでしまうのは致命的な気がします。どうしてユーザ登録画面になってしまうのか時間があれば確認してもらえますか？

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
確認したところ、ホーム画面に戻ることが出来ているのでこの件はクローズします。
