### ISSUE TITLE
SNS連携で別のメールアドレスを登録する場合に確認メールが飛ばない

### ISSUE THREAD

**Issue by ernix** [internship2016/sovolo#346]
メールを入力しただけでis_activeが有効になってしまう？
https://github.com/internship2016/sovolo/pull/342

**Comment by MURAKOSHITAKAHIRO** [comment]
#338

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
Twitter/Facebookで確認メールが飛ぶことを確認しました。
このissuesを閉じます。
