### ISSUE TITLE
Sovol Twitterアカウント登録しようとするとエラーが発生する。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#348]
「Twitter登録」をクリックすると、以下のエラーが発生してしまう。

<img width="1616" alt="2018-06-26 11 53 36" src="https://user-images.githubusercontent.com/34121151/41890694-8a9c4710-794b-11e8-9c64-209b872aec84.png">

**Comment by MURAKOSHITAKAHIRO** [comment]
#338

**Comment by ernix** [comment]
これかもしれん。パッケージをアップデートしてTwitterAPI側の設定を変更しないといけない。
https://github.com/python-social-auth/social-app-django/issues/164#issuecomment-399730181

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO twitterAPIのアカウントを私個人のものに変更し、設定を変更して使えるようになりました。一度確認してもらえますか？

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
登録できました。
<img width="1574" alt="2018-06-27 15 35 29" src="https://user-images.githubusercontent.com/34121151/41956819-eec18c12-7a1f-11e8-8b2a-8fab8a19ba90.png">
<img width="1902" alt="2018-06-27 15 36 01" src="https://user-images.githubusercontent.com/34121151/41956824-f3f5b000-7a1f-11e8-9467-f74e444061b4.png">

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
これは個人のtwitterAPIのアカウントを使っているのですよね。
個人のではなく会社のtwitterAPIのアカウントに変更できるのでしょうか。
