### ISSUE TITLE
Facebook・Twitterのプライバシーポリシー作成

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#349]
facebook apiのフローが変更になるため、プライバシーポリシーをEnglishで作成する。

2018/8/2までにプライバシーポリシーを完成させて、審査を通すまでを完了させる。

**Comment by ernix** [comment]
うーん、参ったね。

詳しく審査の内容を確認してるけど、どうもFacebookからユーザの年齢をひっぱってくる理由とそのテスト方法を詳しく示さないといけないっぽい。
今sovolではユーザの誕生日から「年齢: 30台」のような表記をしてるけど、Facebook的には「それってどうなの？」っていうのが問題の本質。

@MURAKOSHITAKAHIRO sovolで年齢にまつわるユーザパラメータを削除してもいいか考慮してもらえますか？
アメリカなんかだと「企業は就職活動で年齢を要求してはいけない」なんてルールもあるぐらい年齢はセンシティブな情報です。sovolが断りなく誕生日から「この人は何歳台」とか計算してプロフィールで公開するのも当然良くないです。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
年齢の項目を消すぐらいやらないといけないですか。

**Comment by ernix** [comment]
@hejob ユーザのモデルから年齢のパラメータを消せるか確認してもらえますか？Facebookから「なんでお前んとこは生年月日をFacebookから持ってくる必要があるんだ？って言われてる」
しこたまめんどくさいので年齢に関する項目を消してしまいたい。

ここらへん:

```python
    def get_about_age(self):
        today = datetime.today()
        birthday = self.birthday
        age = today.year - birthday.year

        if (today.month, today.day) <= (birthday.month, birthday.day):
            age -= 1

        return math.floor(age / 10) * 10
```

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO そもそもsovolでユーザの年齢をバラす理由が薄い。
作った時は「ソーシャル的な動きをするから年齢が分かった方がいいかな」という感じだったけど、ちょっと扱いが軽率過ぎるとも思う。プロフィールに生年月日を入れたら「この人何歳台でーす！」ってサイトにバラされるなんて普通は思わない。

**Comment by ernix** [comment]
もうひとつ。上の `get_about_age` は誕生日から「何歳台」を計算する関数だけど、ユーザのプロフィールを毎日監視していたら御本人の誕生日も年齢も全部バレるので、ボカシになっていない。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix 
年齢の項目を削除してしまった方がいいと思います。

**Comment by ernix** [comment]
でしょ

**Comment by ernix** [comment]
あー、ボランティア募集側は年齢制限かけたいのか。うーん・・・Twitter/FacebookのSNSログイン自体をやめてしまった方がいいかも。日本的なボランティア募集がアメリカ西海岸のルールに縛られたら本末転倒。

**Comment by MURAKOSHITAKAHIRO** [comment]
生年月日をFacebookから取得するのをやめて、自分で書いてもらうことにします。

**Comment by MURAKOSHITAKAHIRO** [comment]
プライバシーポリシーも以下のURLを使ってください。
https://www.interlink.or.jp/company/privacy.html

**Comment by MURAKOSHITAKAHIRO** [comment]
新たにissuesを作成しました。

◾️Facebookから生年月日を取得するのをやめる · Issue #350 · internship2016/sovolo
https://github.com/internship2016/sovolo/issues/350

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
プライバシーポリシーはあるものを使います。
そのため、プライバシーポリシーのために新たなページを作成やURLに飛ばすということはしなくてもいいです。
そのため、ここをcloseします。
ただ、何らかの問題が発生した場合は再度、openします。
