### ISSUE TITLE
Facebookから生年月日を取得するのをやめる

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#350]
FacebookのAPIで年齢をひっぱってくる理由とそのテスト方法を詳しく示さないといけないため、
審査に通らない可能性が出てきましたので、生年月日については自己申告にして、
Facebookから生年月日を取得しないように改修してください。

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob 
この問題を最優先でお願いします。

**Comment by hejob** [comment]
@ernix 
コード見ましたが、Django-social-authのプラグインを通してFacebookに通信しているようで、
ユーザーモデルとは関係ないはずです。

フィールドに関してはsettingにあったようです：
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'locale': 'ja_JP',
    'fields': 'id, name, email, age_range'
}
生年月日に関するものは見つかりませんでした。おそらくこのage_rangeのことが問題かと思います。
一応PRで修正版提出します。

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob @ernix 
テストした結果。
生年月日を取得していないことを確認しました。
