### ISSUE TITLE
トップページにある以下のリンクを隠してください。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#353]
<img width="430" alt="2018-07-25 16 14 56" src="https://user-images.githubusercontent.com/34121151/43186044-87dd6222-9028-11e8-84f6-947068bf7b39.png">

このようなリンクがありますが、いらないので隠してください。

**Comment by ernix** [comment]
@MURAKOSHITAKAHIRO プロダクション環境から隠す、でいいですか？

**Comment by ernix** [comment]
対応しました:
https://github.com/internship2016/sovolo/commit/6cf99154a0b081a1f277d8340cfb47ebc7f90f1f
