### ISSUE TITLE
ボランティア開始日時が一日ずれてしまう。

### ISSUE THREAD

**Issue by MURAKOSHITAKAHIRO** [internship2016/sovolo#355]
表示されているボランティア開始日時が１日ずれている。
ただしくは８月２５日ですが、２４日になっています。
調査していただけますか。

![snapcrab_noname_2018-8-21_14-57-37_no-00](https://user-images.githubusercontent.com/34121151/44383358-7a729b80-a553-11e8-8be6-59f772d6bb44.png)

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob @ernix 
テストしたところ、再現できました。
時刻が日本の時刻ではなく、標準時刻で表示しているかもしれない事が分かりました。

<img width="1624" alt="2018-08-21 17 14 12" src="https://user-images.githubusercontent.com/34121151/44389686-78660800-a566-11e8-96ed-a3a1bd70f31f.png">
<img width="1622" alt="2018-08-21 17 16 40" src="https://user-images.githubusercontent.com/34121151/44389688-78660800-a566-11e8-8d94-9ef8ecf66998.png">
<img width="1607" alt="2018-08-21 17 16 57" src="https://user-images.githubusercontent.com/34121151/44389689-78660800-a566-11e8-93a2-6b95882049f7.png">
<img width="1606" alt="2018-08-21 17 17 24" src="https://user-images.githubusercontent.com/34121151/44389690-78660800-a566-11e8-85a9-dc9ca74dc759.png">

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 
恐らく、UTCで時刻を表示しているのかもしれません。

**Comment by MURAKOSHITAKAHIRO** [comment]
@ernix @hejob 

修正をお願いします。

**Comment by hejob** [comment]
@MURAKOSHITAKAHIRO こちらも確認しました。
原因はAPIでもらう時刻はUTCで、Timezone情報も付与されていないフォーマットのことです。

**Comment by MURAKOSHITAKAHIRO** [comment]
@hejob 
@ernix 
確認しました。
修正されていますので、closeします。
