### ISSUE TITLE
プロフィール編集画面において、住んでいる都道府県のデフォルト値を、「北海道」から「現在設定している値」に変更する

### ISSUE THREAD

**Issue by haraguchijouji** [internship2016/sovolo#36]
画像選択済み、住んでいる都道府県の既設定情報がデフォルトに戻っている。

**Comment by ernix** [comment]
@haraguchijouji 再現しませんでした。画像を選択した場合に問題が発生するということですか？

**Comment by haraguchijouji** [comment]
プロフィール画面ではＯＫ
プロフィール編集では都道府県のデフォルト値が「現在設定している値」になってないようだ
