### ISSUE TITLE
イベントキャンセルの後、トップページに戻ろうとするとエラー発生

### ISSUE THREAD

**Issue by keitakurita** [internship2016/sovolo#53]
内容：
Reverse for 'participate' with arguments '(20, '')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['event/(?P<event_id>[0-9]+)/participate/(?P<frame_id>[0-9]+)$']
というエラーが発生

再現方法：
・dataをリセットする(python3 manage.py flush, python3 manage.py seed_data)
・所属グループのイベントから、Event #20にアクセス、参加をキャンセルする
・トップページに戻る

**Comment by keitakurita** [comment]
いつの間にか解決していましたが、まだ発生しますでしょうか？

**Comment by tntktnx** [comment]
再現性がない
