### ISSUE TITLE
参加予定のイベントなのに参加するのボタンが存在する

### ISSUE THREAD

**Issue by tasugi** [internship2016/sovolo#65]
これは消して代わりにキャンセルのボタンが欲しい

**Comment by keitakurita** [comment]
再現方法を教えてくれーーーー

**Comment by tasugi** [comment]
generic_user_1とGeneric Event #3の間で問題発生
/event/3/
に参加するボタンがある (; ;)

**Comment by keitakurita** [comment]
僕の環境だと発生しない...なぜだろうか...？？？？

**Comment by tasugi** [comment]
再現しなくなった。データが古かったのかな
