### ISSUE TITLE
画像の整形

### ISSUE THREAD

**Issue by keitakurita** [internship2016/sovolo#7]
正方形に切り出したい

**Comment by ernix** [comment]
croppie.jsを使って正方形に切り出せるようにした。croppieブランチにあげています。

これは副次的に、日本語のファイル名の問題も解決します。
https://github.com/internship2016/sovolo/issues/10

ただし・・・
やっていることが若干hackyというか、通常のPOSTではなくAjax経由になっています。
https://github.com/internship2016/sovolo/commit/87ecf451585ba9e60db8483a3a84ede73942860a

POST時に青の「プロフィールを修正しました」は出てきませんし、
個々のブラウザでサポートされているか詳しく確認する必要があります。

また、Ajax通信時にローディング画像がないと時間のかかる通信に違和感を覚えるかもしれません。

**Comment by ernix** [comment]
croppieブランチをmasterにマージしました
