### ISSUE TITLE
タグの策定

### ISSUE THREAD

**Issue by tntktnx** [internship2016/sovolo#8]

**Comment by ernix** [comment]
もうちょい詳しくお願いします。イベントのタグ？

**Comment by tntktnx** [comment]
solovoにおいて「タグ」は一意です。
そのタグはユーザが自由に作成できるものではなく、事前にサービス側で用意しておくということまで決まっていますが、具体的にどういうタグを用意するかが決まっていないということです。

**Comment by tasugi** [comment]
タグは全角５文字までにしたい

**Comment by tasugi** [comment]
決めた

環境
地域
人権
教育
医療
介護
国際協力
文化
スポーツ
被災者支援
動物
