### ISSUE TITLE
ロゴ・ファビコンなどの作成

### ISSUE THREAD

**Issue by tntktnx** [internship2016/sovolo#9]

**Comment by ernix** [comment]
![logo](https://cloud.githubusercontent.com/assets/343556/17825577/4d98d2b2-661e-11e6-99b4-24169f6fec60.png)

とりあえずこいつで

**Comment by ernix** [comment]
ゴチャゴチャしすぎていたので、Sを強調する形で線を減らしました。
![logo](https://cloud.githubusercontent.com/assets/343556/17840209/9a649c74-67b4-11e6-8d2c-83b2d48ee895.png)

**Comment by ernix** [comment]
ロゴが流石に汚すぎたのでパスを書き直した。

![logo](https://cloud.githubusercontent.com/assets/343556/17990628/530c3824-6aec-11e6-8ad1-545acfb9c35b.png)
